# Generated by Django 4.1 on 2022-08-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0003_alter_item_dono_alter_item_usuario_reserva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
