# Generated by Django 4.1 on 2022-08-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0005_item_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
    ]
