# Generated by Django 4.1 on 2022-08-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0006_remove_item_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='evento',
        ),
        migrations.AddField(
            model_name='item',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bazar.evento'),
            preserve_default=False,
        ),
    ]
